### ISSUE TITLE
What about session 5?

### ISSUE THREAD

**Issue by KPull** [Neurobics/workouts#10]
When shall we hold session 5?

**Comment by ericathedev** [comment]
Depends if we'll be doing it remote or not. :) if remote then any day
Thursday to Sunday, if not Sunday is best.

**Comment by chiarafsc** [comment]
I'm afraid we don't have an internet connection at the flat (could use some mobile internet, but it must be reliable). 

I'll be honest, I prefer a week night!

**Comment by camilleriluke** [comment]
https://github.com/Neurobics/workouts/issues/9 

Just sayin 😄

**Comment by KPull** [comment]
I want to do Kotlin too! We should do katas and programming exercises that lend themselves well to functional-style. The Kotlin reference is very good to read as well: https://kotlinlang.org/docs/reference/.

**Comment by mariacamenzuli** [comment]
Can we do this sometime next week? :)

**Comment by camilleriluke** [comment]
Next week is fine for me. @chiarafsc wanna do that fancy poll you did last time?

**Comment by chiarafsc** [comment]
Voila! http://rallly.co/Vk-2da_IG
Weekends might be a little difficult for me, but I'll see what I can do if we decide to meet up for the next one!

**Comment by FrelliBB** [comment]
Looks like Thursday's the day?

**Comment by camilleriluke** [comment]
Next meetup: **Thursday Jan 26th 2017 9:00pm - 10:15pm**

Cu :v: 💻 

P.S. @KPull any links / steps on how we can set up Kotil? So we don't spend time setting up on the day.

**Comment by KPull** [comment]
I didn't really setup anything. IntelliJ IDEA comes with Kotlin setup itself so it shouldn't be a problem to get started. You can try compiling a Kotlin file to test your configuration. Also, we can try to find Katas online or we can also try these so-colled Koans which JetBrains suggest for getting familiar with Kotlin: https://github.com/Kotlin/kotlin-koans/tree/master/src

**Comment by camilleriluke** [comment]
Dear Neurobians 🌟

📣 ℹ️ **Reminder** ℹ️ 📣 

Session **tonight** on hangouts at **9:00pm**

**Comment by chiarafsc** [comment]
```kotlin
fun main(args: Array<String>) {
    println("Start the warmup!")
}
```

**Comment by chiarafsc** [comment]
Join me on [hangouts!](https://hangouts.google.com/call/nihcyssg35gwdm2ts2s53qth3ie)

**Comment by chiarafsc** [comment]
![screen shot 2017-01-26 at 22 27 45](https://cloud.githubusercontent.com/assets/5637636/22351620/175bc262-e419-11e6-9882-b8c370558a3c.png)
That's all folks! 🙋🏻🌃

**Comment by chiarafsc** [comment]
That's all folks! 🙋🏻🌃

**Comment by KPull** [comment]
Reference manual for further reading: https://kotlinlang.org/docs/reference/basic-syntax.html

**Comment by camilleriluke** [comment]
🚺  and 🚹  that was 🎉  

nice session today :v:

**Comment by ericathedev** [comment]
Great session guys! Have you read this:
http://blog.cleancoder.com/uncle-bob/2017/01/11/TheDarkPath.html what do
you think? :) (still forming an opinion here)

**Comment by ericathedev** [comment]
And there's a follow up article:
http://blog.cleancoder.com/uncle-bob/2017/01/13/TypesAndTests.html

Some people believe in types and that gives us things like TypeScript... Is
it better? Is it not? Etc
