### ISSUE TITLE
Neurobics first meeting

### ISSUE THREAD

**Issue by camilleriluke** [Neurobics/workouts#2]
Let's find a convenient day and time where we can meet for the first time. There are two options; It could be during the week, or during the weekends. I added a few pros and cons for each. Feel free to comment with more pros and cons or any other option you might think is viable.
## Weekdays

| Pros | Cons |
| --- | --- |
| 5 out of 7 OMG! | Might be tired after work |
|  | Everyone works on different schedules |
|  | We might be hungry |
## Weekends

| Pros | Cons |
| --- | --- |
| More hours, almost any time during the day | We get only 2 of them |

**Comment by camilleriluke** [comment]
Pinging @Neurobics/everyone for visibility. 

Feedback on when we can kickstart this?

**Comment by ericathedev** [comment]
Next week I have plans on Wednesday and Saturday. The rest are free. What days are you guys available?

**Comment by FrelliBB** [comment]
I have plans on Monday and Thursday so far. Should be okay for the rest.

**Comment by ericathedev** [comment]
Is everyone free on Tuesday? Are we doing this remotely or IRL?

**Comment by KPull** [comment]
We can do it Tuesday.

**Comment by chiarafsc** [comment]
Tuesday sounds good!!

**Comment by camilleriluke** [comment]
Tuesday 30th it is (starting at 7:00pm).

Next question: Remote or IRL?

Some things to keep in mind:

#### IRL
- Big screen
- Space where we can all fit
- Place that doesn't mind the noise we will be making

#### Remote
- Everyone should setup their IDE beforehand
- Good internet connection

**Comment by camilleriluke** [comment]
### Points for next time
- Start on time
- No remote (Pullicin's wifi ~~maltese internet~~ connection is SHIT)
- One laptop, one screen
- Monitor was a plus
- When the connection was good, the flow was amazing!
- Sessions should run for 2.5h (2 turns of 10min each)
- Will meet again 8th Sep 14:00hrs
- Where? Airport? Microsoft Innovation Center?

**Comment by camilleriluke** [comment]
Edit: Updated points for next time
