### ISSUE TITLE
Second meeting 🐲

### ISSUE THREAD

**Issue by ericathedev** [Neurobics/workouts#4]
It's time to start thinking about our next meeting. We will be continuing from where we left off last time. 

Date: **Thursday 8th September 2pm** 
### Open questions
- [x] Where are we going to meet? - (Ask @chiarafsc for more info)

Pinging @Neurobics/everyone for visibility.

**Comment by camilleriluke** [comment]
Update your IDEs and download all the things you need beforehand since we are going to be on 3G.

Cu in a couple of hours neurobists 🌈

**Comment by chiarafsc** [comment]
Yes sir! Looking forward. See you then :)

**Comment by camilleriluke** [comment]
🦄

**Comment by KPull** [comment]
Good job. We had some very insightful discussions.

**Comment by ericathedev** [comment]
### Meeting notes

Good:
- no hardware issues this meeting 
- good that 1 person was responsible for time on rotation 

Improvements:
- keyboard and keyboard formats
- not having a plan means we spend a long time discussing. Sometimes people do not get to code ato all in their 10 mins slot. Improvements: give people another slot (let them speak in between), time does not start until person codes their first word.
- need to be stricter about not speaking
- grew tired after 2 hrs

Had a great time people,  looking forward to the next one :smile:
