### ISSUE TITLE
Third meeting 🐣

### ISSUE THREAD

**Issue by ericathedev** [Neurobics/workouts#6]
Dear Neurobians,

It is time to decide the date for our third meeting! I believe someone mentioned next weekend is not convenient for them so I suggest 29th/30th October. Is everyone free? 😄 

Ping @Neurobics/everyone 😸

**Comment by chiarafsc** [comment]
I'll be in Gozo for a wedding next weekend. I have some vague plans the weekend of 29/30, but it should be possible to plan around it.

**Comment by ericathedev** [comment]
If people are busy in the weekend we can also consider weekends 😄

**Comment by chiarafsc** [comment]
*weekdays! Yes you're right! Any time during the next two weeks then.

**Comment by FrelliBB** [comment]
I will not be available from 27th October till ~5th November

**Comment by KPull** [comment]
29/30 Oct sounds good to me. :)

**Comment by ericathedev** [comment]
Okay guys, let's try this again... Next weekend, November 12th/13th? 😄

**Comment by chiarafsc** [comment]
Can only make it in the morning on the 12th, but the 13th is still free :)

**Comment by FrelliBB** [comment]
Sound be free for both

**Comment by KPull** [comment]
Fine by me.

**Comment by camilleriluke** [comment]
👍

**Comment by chiarafsc** [comment]
So? :P

**Comment by camilleriluke** [comment]
Currently 13th is a good contender.

@maria-camenzuli what's your availability?

**Comment by mariacamenzuli** [comment]
The 13th is ok for me :)

**Comment by camilleriluke** [comment]
So... We have a date everyone! 🎉  Cu on **Sunday 13th**.

Now we just need to agree on a time and place.

**Comment by ericathedev** [comment]
Everyone available at 5pm, at Chiara's place like last time?

**Comment by KPull** [comment]
Ok. :)

**Comment by camilleriluke** [comment]
Awesome session last Sun :) 

![awesomesession](https://cloud.githubusercontent.com/assets/1117126/20296611/2d0e9008-ab0c-11e6-84dc-a4502e559ed5.gif)

I feel that the fact that we switched to working on an small closed workouts made it more pleasant and satisfying.

**Comment by camilleriluke** [comment]
Last session's code https://github.com/Neurobics/gym/commit/840fcf1a752085bd2d39f6512fe35bf060759d60
