### ISSUE TITLE
Let's schedule workout 4!

### ISSUE THREAD

**Issue by chiarafsc** [Neurobics/workouts#8]
Please enter your availabilities for next week! Would be cool if we could try this remotely. 
http://rallly.co/412NGbXbz

**Comment by camilleriluke** [comment]
✅

**Comment by ericathedev** [comment]
Hey all - sorry I didn't reply on this, it's been a crazy week :) And next week promises to be the same :) How would you guys feel like a _remote_ neurobics tomorrow? The weather should be horrible anyway, perfect weather to stay inside.

**Comment by chiarafsc** [comment]
I don't think I'll be able to make it tomorrow 😶 let's try a weekday!

**Comment by KPull** [comment]
I'm not going to be available tomorrow. Sorry.

**Comment by chiarafsc** [comment]
Kyle still has to mark his availabilities in the form. We're looking at
tomorrow, Wednesday or Thursday!

**Comment by KPull** [comment]
Marked.

**Comment by ericathedev** [comment]
So Thursday it is? :)

**Comment by camilleriluke** [comment]
That is what the peoplez wants! 
Now we need to agree on the 🕐 , suggestions?

**Comment by ericathedev** [comment]
Since at work we're discussing traffic etc... How about after dinner, at 8pm/9pm for 1hr. Everyone can get home and eat in peace before starting?

**Comment by KPull** [comment]
Ok :)

**Comment by camilleriluke** [comment]
Good for me 😃

**Comment by chiarafsc** [comment]
Good!

**Comment by ericathedev** [comment]
So we will meet up online at 8,  set up and officially start at 8:30. :)

**Comment by camilleriluke** [comment]
Please make sure:
- 💻 to set up your IDEs beforehand.
- :octocat: download the gym repo (https://github.com/Neurobics/gym).
- ✅ run the tests to make sure you're ready to go.

**Comment by ericathedev** [comment]
Note: If you pull and build you will find that an assertion in Harry Potter is failing.

If we are interested in trying Conway's Game of Life a 2 min explanation can be found here: https://www.youtube.com/watch?v=0XI6s-TGzSs 😄

**Comment by chiarafsc** [comment]
https://hangouts.google.com/group/9xF8Sq1BMdT5dgPx1

**Comment by ericathedev** [comment]
https://github.com/garora/TDD-Katas
